export const WEIGHTS = {
  PRIMARY_GOAL: 3,
  HEALTH_CONCERN: 2,
  CATEGORY_MATCH: 1.5,
  THERAPEUTIC_CLAIM: 1,
  SYNERGY_BOOST: 1.5,
  MISMATCH_PENALTY: 0.5,
  MIN_CONFIDENCE: 80,
  MAX_CONFIDENCE: 100,
  MIN_CATEGORIES: 2,
  MAX_PRODUCTS_PER_CATEGORY: 2,
  MIN_RECOMMENDATIONS: 3
};

export const PRODUCT_SYNERGIES = {
  BRAIN_HEALTH: ['focus', 'omega-3'],
  SLEEP_STRESS: ['magnesium', 'melatonine']
};