export type ProductCategory = 
  | "relaxation" 
  | "sommeil" 
  | "stress" 
  | "digestif" 
  | "santé_générale" 
  | "cerveau" 
  | "concentration" 
  | "énergie" 
  | "santé_cheveux" 
  | "peau" 
  | "immunité" 
  | "muscles" 
  | "articulations" 
  | "ongles" 
  | "hormones"
  | "thyroïde" 
  | "santé_femme" 
  | "santé_homme" 
  | "migraine"
  | "douleur" 
  | "guérison" 
  | "topique" 
  | "immunité" 
  | "saisonnier" 
  | "gorge" 
  | "essentiel" 
  | "santé_osseuse" 
  | "enfants" 
  | "métabolisme" 
  | "santé_cardiaque" 
  | "court_terme" 
  | "long_terme";

export type TimeFrame = "court_terme" | "long_terme";
export type Season = "hiver" | "printemps" | "été" | "automne" | "toute_année";
